[2023-06-27 10:13:58,135][MainThread:25540][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 10:14:26,477][Thread-1:35528][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 16, in post
    screen_shot = AutoScreenshot(code=code, links=links)
TypeError: __init__() got an unexpected keyword argument 'links'
[2023-06-27 10:14:26,477][Thread-1:35528][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 16, in post
    screen_shot = AutoScreenshot(code=code, links=links)
TypeError: __init__() got an unexpected keyword argument 'links'
[2023-06-27 10:15:12,837][MainThread:25540][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 10:15:14,186][MainThread:45768][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 10:18:02,829][MainThread:45768][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 10:19:07,202][MainThread:39588][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 10:19:19,116][MainThread:39588][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 10:19:20,121][MainThread:17084][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 10:21:21,859][MainThread:17084][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 10:21:23,035][MainThread:14548][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 10:21:52,189][Thread-1:42356][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 16, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 58, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 42, in screenshot
    self.results.append(base64.b64encode(screenshot_bytes).decode("utf-8"))
  File "C:\Program Files\python3.9\lib\base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'coroutine'
[2023-06-27 10:21:52,189][Thread-1:42356][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 16, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 58, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 42, in screenshot
    self.results.append(base64.b64encode(screenshot_bytes).decode("utf-8"))
  File "C:\Program Files\python3.9\lib\base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'coroutine'
[2023-06-27 10:24:32,743][MainThread:14548][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 10:24:34,035][MainThread:28440][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 10:25:08,068][Thread-1:28736][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 16, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 59, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 43, in screenshot
    self.results.append(base64.b64encode(screenshot_bytes).decode("utf-8"))
  File "C:\Program Files\python3.9\lib\base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'coroutine'
[2023-06-27 10:25:08,068][Thread-1:28736][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 16, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 59, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 43, in screenshot
    self.results.append(base64.b64encode(screenshot_bytes).decode("utf-8"))
  File "C:\Program Files\python3.9\lib\base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'coroutine'
[2023-06-27 10:25:35,052][MainThread:28440][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 10:25:35,932][MainThread:45944][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 10:27:47,927][MainThread:45944][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 10:27:48,966][MainThread:43920][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 10:28:16,275][Thread-1:28632][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 16, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 59, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 42, in screenshot
    screenshot_bytes = await page.screenshot(f"{time.time()}.png")
TypeError: screenshot() takes 1 positional argument but 2 were given
[2023-06-27 10:28:16,275][Thread-1:28632][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 16, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 59, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 42, in screenshot
    screenshot_bytes = await page.screenshot(f"{time.time()}.png")
TypeError: screenshot() takes 1 positional argument but 2 were given
[2023-06-27 10:29:20,843][MainThread:43920][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 10:29:21,754][MainThread:38596][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 10:31:54,177][MainThread:38596][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 10:31:55,122][MainThread:21076][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 10:32:00,033][MainThread:21076][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 10:32:01,138][MainThread:43048][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 10:33:12,829][Thread-1:44272][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 16, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 60, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 42, in screenshot
    await i.scroll_into_view_if_needed(timeout=30000)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17270, in scroll_into_view_if_needed
    await self._impl_obj.scroll_into_view_if_needed(timeout=timeout)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 531, in scroll_into_view_if_needed
    return await self._with_element(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 119, in _with_element
    return await task(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_element_handle.py", line 102, in scroll_into_view_if_needed
    await self._channel.send("scrollIntoViewIfNeeded", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 29907ms exceeded.
=========================== logs ===========================
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 0ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 50ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 100ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 250ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
============================================================
[2023-06-27 10:33:12,829][Thread-1:44272][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 16, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 60, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 42, in screenshot
    await i.scroll_into_view_if_needed(timeout=30000)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 17270, in scroll_into_view_if_needed
    await self._impl_obj.scroll_into_view_if_needed(timeout=timeout)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 531, in scroll_into_view_if_needed
    return await self._with_element(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 119, in _with_element
    return await task(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_element_handle.py", line 102, in scroll_into_view_if_needed
    await self._channel.send("scrollIntoViewIfNeeded", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 29907ms exceeded.
=========================== logs ===========================
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 0ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 50ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 100ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 250ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
  waiting for element to be  and stable
  element is  and stable
  element is not displayed, retrying in 500ms
============================================================
[2023-06-27 10:37:38,137][MainThread:43048][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 10:37:39,316][MainThread:26724][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 10:37:50,257][MainThread:26724][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 10:37:51,583][MainThread:17276][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 10:42:55,284][MainThread:17276][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 10:42:56,205][MainThread:15004][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 10:44:00,972][MainThread:15004][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 10:44:02,380][MainThread:20248][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 10:46:24,050][MainThread:20248][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 10:46:25,253][MainThread:32216][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 10:48:30,248][MainThread:32216][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 10:48:31,239][MainThread:18940][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 10:49:07,926][MainThread:18940][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 10:49:08,853][MainThread:42512][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 10:50:38,639][MainThread:42512][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 10:50:39,573][MainThread:40956][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 10:51:52,837][Thread-1:45180][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 16, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 64, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 48, in screenshot
    self.results.append(screenshot_bytes.decode("utf-8"))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
[2023-06-27 10:51:52,837][Thread-1:45180][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 16, in post
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 64, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 48, in screenshot
    self.results.append(screenshot_bytes.decode("utf-8"))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
[2023-06-27 10:52:47,372][MainThread:40956][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 10:52:48,884][MainThread:17880][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 10:53:43,571][MainThread:17880][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 10:53:44,625][MainThread:19292][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 10:54:53,875][MainThread:19292][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 10:54:54,628][MainThread:3532][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 10:58:07,245][MainThread:3532][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 10:58:08,325][MainThread:17308][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 11:01:34,607][MainThread:17308][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 11:01:35,992][MainThread:43920][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 11:07:36,119][MainThread:43920][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 11:07:37,233][MainThread:36980][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 11:12:31,191][MainThread:36980][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\views.py changed, reloading.]
[2023-06-27 11:12:33,205][MainThread:42828][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 11:18:02,429][MainThread:42828][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 11:18:03,477][MainThread:43304][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 11:19:23,421][Thread-1:27776][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 65, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 48, in screenshot
    screenshot_bytes = await page.screenshot(f"{time.time()}.png")
TypeError: screenshot() takes 1 positional argument but 2 were given
[2023-06-27 11:19:23,421][Thread-1:27776][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 65, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 48, in screenshot
    screenshot_bytes = await page.screenshot(f"{time.time()}.png")
TypeError: screenshot() takes 1 positional argument but 2 were given
[2023-06-27 11:26:09,361][MainThread:43304][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 11:26:10,929][MainThread:45272][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 11:32:01,575][MainThread:45272][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 11:32:03,183][MainThread:41384][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 11:33:13,209][Thread-1:18344][task_id:FacebookScreenshot.facebookplaywright][facebookplaywright.py:41][INFO][未清除内容，图片可能出现冗余]
[2023-06-27 11:38:36,849][MainThread:41384][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 11:38:37,966][MainThread:41048][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 14:02:59,485][MainThread:41048][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 14:03:00,492][MainThread:49424][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 14:05:02,060][MainThread:49424][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 14:05:03,504][MainThread:51032][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 14:06:14,274][MainThread:51032][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 14:06:15,264][MainThread:51940][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 14:09:16,515][MainThread:51940][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 14:09:17,521][MainThread:47056][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 14:09:36,577][Thread-1:47236][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 73, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 35, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_PROXY_CONNECTION_FAILED at https://www.facebook.com/search/top/?q=75J7RQFX
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-27 14:09:36,577][Thread-1:47236][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 73, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 35, in screenshot
    await page.goto(f'https://www.facebook.com/search/top/?q={self.code}')
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9204, in goto
    await self._impl_obj.goto(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 495, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 147, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_PROXY_CONNECTION_FAILED at https://www.facebook.com/search/top/?q=75J7RQFX
=========================== logs ===========================
navigating to "https://www.facebook.com/search/top/?q=75J7RQFX", waiting until "load"
============================================================
[2023-06-27 14:10:53,072][Thread-1:47236][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 73, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 42, in screenshot
    if page.get_by_text("展开").count() > 0:
TypeError: '>' not supported between instances of 'coroutine' and 'int'
[2023-06-27 14:10:53,072][Thread-1:47236][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 73, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 42, in screenshot
    if page.get_by_text("展开").count() > 0:
TypeError: '>' not supported between instances of 'coroutine' and 'int'
[2023-06-27 14:11:36,996][MainThread:47056][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 14:11:38,419][MainThread:51340][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 14:12:27,067][Thread-1:22424][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 73, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 51, in screenshot
    await i.click()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 15419, in click
    await self._impl_obj.click(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 160, in click
    return await self._frame.click(self._selector, strict=True, **params)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 489, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for get_by_text("展开").nth(1)
============================================================
[2023-06-27 14:12:27,067][Thread-1:22424][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 73, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 51, in screenshot
    await i.click()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 15419, in click
    await self._impl_obj.click(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 160, in click
    return await self._frame.click(self._selector, strict=True, **params)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 489, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for get_by_text("展开").nth(1)
============================================================
[2023-06-27 14:14:51,074][MainThread:51340][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 14:14:52,320][MainThread:49932][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 14:15:19,256][Thread-1:11096][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 74, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 52, in screenshot
    await i.click(timeout=5000)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 15419, in click
    await self._impl_obj.click(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 160, in click
    return await self._frame.click(self._selector, strict=True, **params)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 489, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 5000ms exceeded.
=========================== logs ===========================
waiting for get_by_text("展开").nth(1)
============================================================
[2023-06-27 14:15:19,256][Thread-1:11096][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 74, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 52, in screenshot
    await i.click(timeout=5000)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 15419, in click
    await self._impl_obj.click(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_locator.py", line 160, in click
    return await self._frame.click(self._selector, strict=True, **params)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_frame.py", line 489, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 5000ms exceeded.
=========================== logs ===========================
waiting for get_by_text("展开").nth(1)
============================================================
[2023-06-27 14:15:43,159][MainThread:49932][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 14:15:44,062][MainThread:33132][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 14:16:30,640][MainThread:33132][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 14:16:31,583][MainThread:51992][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 14:22:42,380][MainThread:51992][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 14:22:43,729][MainThread:47040][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 14:25:59,404][MainThread:47040][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 14:26:00,938][MainThread:2312][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 14:29:20,817][MainThread:2312][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 14:29:21,792][MainThread:16512][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 14:34:03,970][MainThread:16512][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 14:34:05,583][MainThread:29832][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 14:39:15,056][MainThread:29832][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 14:39:16,124][MainThread:51880][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 14:40:06,327][Thread-1:48052][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 78, in run
    await self.login(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 33, in login
    await expect(page.get_by_label("首页")).to_be_visible()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 20170, in to_be_visible
    await self._impl_obj.to_be_visible(visible=visible, timeout=timeout)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_assertions.py", line 623, in to_be_visible
    await self._expect_impl(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_assertions.py", line 65, in _expect_impl
    raise AssertionError(f"{out_message}\nActual value: {actual} {log}")
AssertionError: Locator expected to be visible
Actual value: False 
Call log:
LocatorAssertions.to_be_visible with timeout 5000ms
waiting for get_by_label("首页")
  locator resolved to <a href="/" role="link" tabindex="0" aria-label="首页…>…</a>
  unexpected value "hidden"
[2023-06-27 14:40:06,327][Thread-1:48052][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 78, in run
    await self.login(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 33, in login
    await expect(page.get_by_label("首页")).to_be_visible()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 20170, in to_be_visible
    await self._impl_obj.to_be_visible(visible=visible, timeout=timeout)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_assertions.py", line 623, in to_be_visible
    await self._expect_impl(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_assertions.py", line 65, in _expect_impl
    raise AssertionError(f"{out_message}\nActual value: {actual} {log}")
AssertionError: Locator expected to be visible
Actual value: False 
Call log:
LocatorAssertions.to_be_visible with timeout 5000ms
waiting for get_by_label("首页")
  locator resolved to <a href="/" role="link" tabindex="0" aria-label="首页…>…</a>
  unexpected value "hidden"
[2023-06-27 14:40:28,968][MainThread:51880][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 14:40:30,074][MainThread:48720][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 14:42:57,798][Thread-1:29680][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 64, in screenshot
    screenshot_bytes = await page.screenshot(path=f"{time.time()}.png")
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9923, in screenshot
    await self._impl_obj.screenshot(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 676, in screenshot
    encoded_binary = await self._channel.send("screenshot", params)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
taking page screenshot
============================================================
[2023-06-27 14:42:57,798][Thread-1:29680][task_id:django.request][log.py:241][ERROR][Internal Server Error: /facebookWebsite/facebook]
Traceback (most recent call last):
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\python3.9\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Program Files\python3.9\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\AutoTestCode(1)\FacebookScreenshot\views.py", line 15, in get
    results = asyncio.run(screen_shot.run())
  File "C:\Program Files\python3.9\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\python3.9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 81, in run
    await self.screenshot(context)
  File "F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py", line 64, in screenshot
    screenshot_bytes = await page.screenshot(path=f"{time.time()}.png")
  File "C:\Program Files\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 9923, in screenshot
    await self._impl_obj.screenshot(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_page.py", line 676, in screenshot
    encoded_binary = await self._channel.send("screenshot", params)
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Program Files\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
taking page screenshot
============================================================
[2023-06-27 14:43:47,544][MainThread:48720][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 14:43:49,252][MainThread:21792][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 14:46:45,838][MainThread:21792][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 14:46:47,626][MainThread:48332][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
[2023-06-27 14:47:21,800][MainThread:48332][task_id:django.utils.autoreload][autoreload.py:266][INFO][F:\AutoTestCode(1)\FacebookScreenshot\facebookplaywright.py changed, reloading.]
[2023-06-27 14:47:23,918][MainThread:42688][task_id:django.utils.autoreload][autoreload.py:668][INFO][Watching for file changes with StatReloader]
